services:
  # Web Service GRATUIT en mode webhook
  - type: web
    name: telegram-bot-webhook
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: WEBHOOK_URL
        sync: false
        value: https://telegram-bot-webhook.onrender.com
      - key: PORT
        sync: false
        value: 10000
      - key: MONGODB_URI
        sync: false
        value: mongodb+srv://coffeelivraison4:FCiljtFGv5iKaKL3@pariscoffee.x0f0tsy.mongodb.net/test?retryWrites=true&w=majority&appName=Pariscoffee
        
  # Note: Le mode webhook est recommandé pour Render (gratuit)
  # Le bot configurera automatiquement le webhook au démarrage